name: thesis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.23,<2.0
  - pillow>=9.5,<11.0
  - scikit-image>=0.20,<0.23
  - scikit-fmm>=2022.5
  - networkx>=2.8,<3.4
  - matplotlib>=3.7,<3.9
  - scipy>=1.10,<1.12
  - scikit-learn>=1.3,<1.5
  - opencv
  - pip:
      - -r requirements.txt
